language: node_js
node_js:
  - "0.10"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - npm install -g grunt-cli  
  - npm install -g bower
  - bower install
before_deploy: "echo 'empieza el deploy'"  
deploy:
  provider: heroku
  app: vacacionespermanentesvy
  api_key: ffac8c94-3488-4db2-8302-b14e7b731efd
after_deploy: "echo 'termino el deploy'"    